title: Krish Kankure # your name (or website title) here
logo: "/images/krishlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am pursuing a BS in Data Science at Purdue University.
  
  <br><br>
  I am currently seeking Data Science and Machine Learning opportunities.  
  <br><br>
  <a href="https://www.linkedin.com/in/krishkankure/">Linkedin</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
